spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

general:
  kafka-topic: trader-updates

logging:
  level:
    com.jpmc.midascore: DEBUG
    org.springframework.kafka: DEBUG